### ISSUE TITLE
Animation is over

### ISSUE THREAD

**Issue by Sler69** [digital-flowers/react-animated-css#12]
The library is awesome I love the implementation. I was just wondering if there is a way to know if the animation is over?

**Comment by digital-flowers** [comment]
Sorry at moment you can't because it's css animation

**Comment by ikhilko** [comment]
@digital-flowers why not? You can listen for animation using `onAnimationEnd` (not sure, but react have such synthetic event) or manually adding event listener for `onanimationend` dom event.

**Comment by digital-flowers** [comment]
@ikhilko if you can help in that would be glad to add you as a contributor
