### ISSUE TITLE
How to use it with react router

### ISSUE THREAD

**Issue by mrsaeeddev** [digital-flowers/react-animated-css#15]
There's an issue with me using react-animated-css with react-router. I am currently wrapping <Route/> Components with <Animated/> like this: `<Animated animationIn="slideInRight" animationOut="slideOutLeft" isVisible={true}>
                <Route exact path="/somepath" component={someComponent} />
                </Animated>` 
It works fine when I am using it with components not defined on explicit routes but when I am using It on components while changing routes the animations don't work on init. However when I reload the same component the animation works on init.

**Comment by digital-flowers** [comment]
If I understand what you are trying to do, I think the `<Animated/>` component need to be inside the route (in the render of SomeComponent)

**Comment by mrsaeeddev** [comment]
I am doing the same like you suggested...its working fine on components with out routing but on components who have separate routes defined for them, Animations don't work on them in the same way i.e wrapping top div of my someComponent with Animated Component..I guess i needs to be done in some lifecycle events in React but I cannot exactly figure out how to do that..

**Comment by digital-flowers** [comment]
if you can share some code example
