### ISSUE TITLE
animation on scroll

### ISSUE THREAD

**Issue by Tricia23** [digital-flowers/react-animated-css#16]
How do I animate the object on scrolling, I'm still a beginner at coding.

**Comment by digital-flowers** [comment]
just use my other component [react-animated-css-onscroll](https://github.com/digital-flowers/react-animated-css-onscroll) ;) 
Using that component you can wrap your elements with that component and they will automatically animate once they enter the screen or leave it, Actually, this is the purpose of this library just follow the readme and check this [demo](https://digital-flowers.github.io/react-animated-css-onscroll.html) and let me know if you have managed to know how to use it
