### ISSUE TITLE
"this.props" vs "nextProps"

### ISSUE THREAD

**Issue by i-chet** [digital-flowers/react-animated-css#17]
Are you sure that's OK to use `this.props` in the [103](https://github.com/digital-flowers/react-animated-css/blob/master/src/index.js#L103) line? I need to have different animationOut effects for two different buttons and `this.props` disable this ability. When I changed it to `nextProps` it start work fine.

**Comment by digital-flowers** [comment]
If you want you can fork this library and do a pull request and i can accept it

**Comment by digital-flowers** [comment]
I think this issue now fixed
