### ISSUE TITLE
Animate out not working?

### ISSUE THREAD

**Issue by NJCA88** [digital-flowers/react-animated-css#21]
Tried on safari and chrome nothing happened when component unmounts

**Comment by digital-flowers** [comment]
The animation will not work if the component is unmounted, it will work when you toggle the `isVisible` property from `true` to `false` and the unmount will be handled internally

**Comment by NJCA88** [comment]
Thanks for the response!  Hmm, when I try to toggle the `isVisible` prop, I get an error saying its read only and can't be changed.  Any thoughts?

**Comment by digital-flowers** [comment]
If you can share an example that would be helpful

**Comment by panjigemilang** [comment]
I've got a problem with animationOut too. please check this link to see my full explanation about :

https://stackoverflow.com/questions/57797371/animatecss-animationout-not-working-it-just-popout

to summaries, the `animationOut` didn't work. I'm using the `isVisible` dynamically but it won't work.
