### ISSUE TITLE
Unable to build with GatsbyJS due to react-prefixer using window and document

### ISSUE THREAD

**Issue by GlenHughes** [digital-flowers/react-animated-css#22]
Hello,

I've been playing around with GatsbyJS lately and have built an example site for learning. I've always used animated.css for animations and never had a problem. Unfortunately, due to one of your dependencies `react-prefixer` which is no longer maintained: https://www.npmjs.com/package/react-prefixer it accesses window and document which in the GatsbyJS world at build time doesn't exist as its in Node and not in a browser.

PR: https://github.com/rapid7/react-prefixer/pull/10

The fix is actually quite simple and I have created a PR to solve this but as the package is no longer maintained I don't know if this will ever be merged. Are you able to use a different package or remove it entirely?

I'm happy to help where I can, just let me know :)

**Comment by digital-flowers** [comment]
I am open for any library suggestions maybe we can copy the prefixer code to this library

**Comment by digital-flowers** [comment]
@GlenHughes I have published a new version 1.2.0 I think this will fix your SSR issue

**Comment by GlenHughes** [comment]
@digital-flowers that did indeed fix it, thanks a lot :)

**Comment by digital-flowers** [comment]
@GlenHughes  thanks for your contribution :)
