### ISSUE TITLE
Safari animation issue

### ISSUE THREAD

**Issue by dhameergovind** [digital-flowers/react-animated-css#3]
Hi there

I am having an issue wth safari where the bounce effect is going crazy. The animations is extremely fast. These are the code snippets I have been using

//JSX
`        <Animated animationIn="bounce" animationOut="bounce" isVisible={true} style={styles.animationTime}>
        <VisaContainer />
        </Animated>`

//css
`      animationDuration: '15s, 30s, 200ms',
      animationIterationCount: 'infinite',`

It works fine on Chrome

**Comment by digital-flowers** [comment]
@dhameergovind  is it working fine with other animation effects ?

**Comment by dhameergovind** [comment]
@digital-flowers just tested, it's doing the same super-fast movement on any animation. Here is a little screen recording of it using the swing animation.

https://www.dropbox.com/s/v3k27qxup27ocil/animatedcss.mov?dl=0

**Comment by digital-flowers** [comment]
i have tested my demo page https://digital-flowers.github.io/react-animated-css.html on Safari and it is working fine, do you have any public page for your page so i can debug it for you ?

**Comment by dhameergovind** [comment]
ok thanks @digital-flowers 

I found the issue, it was this line
`animationDuration: '15s, 30s, 200ms',`

For some reason Safari only read the last value i.e 200ms, so I just left it as 
`animationDuration: '15s',`

and it works fine

Thank you for this library, it's really awesome

**Comment by digital-flowers** [comment]
Glad you found the issue 👍 
You are welcome :)
