### ISSUE TITLE
This library is DEAD?

### ISSUE THREAD

**Issue by hugolfreitas** [digital-flowers/react-animated-css#33]
answer please...
😞

**Comment by andrewdyer** [comment]
This library does not support Animate.css v4.x, which brought some breaking changes. So yes, it is dead. To get this library to work you need to install animate.css v3.x using `npm i animate.css@^3.7.2 --save` or `yarn add animate.css@^3.7.2` or the using the [cdn](https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css). Hope this helps!

**Comment by iamtekson** [comment]
Is this library going to update with Animate.css v4.x and react 17.x?

**Comment by yim222** [comment]
> npm i animate.css@^3.7.2 --save

And after installing what to do ?

**Comment by ayoubkhan558** [comment]
Can somebody please suggest another working library?

**Comment by ayoubkhan558** [comment]
> Is this library going to update with Animate.css v4.x and react 17.x?

Its working with Reactjs 18.0

**Comment by ayoubkhan558** [comment]
Also it is working for me with animate version 4.0
Include
`<linkrel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.compat.css"/>`

instead of
`<linkrel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>`
