### ISSUE TITLE
Not able to hide animation on reload

### ISSUE THREAD

**Issue by mersed** [digital-flowers/react-animated-css#5]
How to hide animation during initial page reload?

When I set **animateOnMount: false**, it will not animate during initial page load indeed, but every single time when you perform animation after that, after animation the animated block will disappear.

Basically, idea is to have element hidden initially, and then animate (in and out) for specific events.

Any ideas how to resolve this?

**Comment by digital-flowers** [comment]
just set the property `isVisible={false}` for the element and when you want the animation to start change it to `isVisible={true}`

**Comment by oleks-fedotov** [comment]
unfortunately, this doesn't help. Setting `isVisible={false}` doesn't prevent the element to be hidden on the initial page load. I tried to use `animateOnMount={false}` together with `isVisible` prop, during the initial page load everything is fine and element is hidden. In- and Out-animations are also performing fine, but between them the element becomes hidden - atm it is the only problem to be solved. 

Any ideas how to solve that?

**Comment by digital-flowers** [comment]
I use this component in a production project and it's working fine  if you can provide code example I can help you with this

**Comment by mersed** [comment]
At the end, I used animation.css and created component by myself.
