### ISSUE TITLE
loop for the effect

### ISSUE THREAD

**Issue by kowalus23** [digital-flowers/react-animated-css#7]
Hello there,

is there any chance to set it in loop, for example to build Interval that refreshing animation every let's say 10sec? Was trying to mount isVisible true/false with Interval but it didnt helped. If you can help in that case, it would be really great. Thanks in advance!

**Comment by digital-flowers** [comment]
it should work, did you see the demo, I guess your time should update a boolean variable in your component state and then pass this state variable to this component isVisible, if you can share your code i can help

**Comment by kowalus23** [comment]
Actually i found out how to do that, but thanks anyway. Maybe in next project i'll try to make it less complicated, then i will poke you! Besides, you did great work!

**Comment by digital-flowers** [comment]
Anw you are welcome
