### ISSUE TITLE
Control duration

### ISSUE THREAD

**Issue by PaulRBerg** [digital-flowers/react-animated-css#9]
Playing around with the `fadeIn` and `fadeOut` animations, I find them rather slow. Is there any option to control duration, other than using the solution proposed here?https://github.com/daneden/animate.css/issues/357?

**Comment by digital-flowers** [comment]
I think if you pass "animation-duration" to the style property it should work for now but yes you need to pass vendor css attribute, something like:

```javascript
<Animated style={{
  animationDuration:"0.5s",
  msAnimationDuration:"0.5s",
  WebkitAnimationDuration:"0.5s",
  MozAnimationDuration:"0.5s",
  OAnimationDuration:"0.5s"
}}>
Hello World
<Animated>
```

for more information see here: [https://zhenyong.github.io/react/tips/inline-styles.html](https://zhenyong.github.io/react/tips/inline-styles.html)
also you can create a function to return this object or use any prefix library

**Comment by smonff** [comment]
Very useful, could be added to the doc.

**Comment by pacientk** [comment]
> Very useful, could be added to the doc.

+1

**Comment by Aashir1** [comment]
I have simply added react-animated-css and run given example but it is not working at all even I have been try above given example.
` <Animated style={{`
` animationDuration:"0.5s", `
` msAnimationDuration:"0.5s", `
` WebkitAnimationDuration:"0.5s", `
` MozAnimationDuration:"0.5s", `
` OAnimationDuration:"0.5s" `
`}}>`
` Hello World `
` <Animated> `

**Comment by digital-flowers** [comment]
@Aashir1  did you added the effect you want, like `fadeIn` ?

**Comment by Aashir1** [comment]
> @Aashir1 did you added the effect you want, like `fadeIn` ?
Thanks for response. I simply used this code.
`<Animated animationIn="fadeInLeft" animationInDelay={0.3} isVisible={true}>`
           ` <div className='heading'>`
            `   ABOUT`
          `</div>`
          `</Animated>`

**Comment by digital-flowers** [comment]
Now the new version has a duration
